# Generated by Django 5.2.12 on 2026-03-28 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(db_index=True, max_length=255)),
                ('district', models.CharField(blank=True, db_index=True, max_length=128)),
                ('rationale', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('district_key', models.CharField(db_index=True, max_length=128)),
                ('district', models.CharField(db_index=True, max_length=128)),
                ('indicator', models.CharField(blank=True, db_index=True, max_length=255)),
                ('attribute_2', models.CharField(blank=True, max_length=255)),
                ('severity', models.IntegerField(blank=True, db_index=True, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('source_file', models.CharField(blank=True, max_length=512)),
            ],
            options={
                'ordering': ['district', 'indicator', 'name'],
            },
        ),
    ]
